---
title: "Final Project"
author: "Lydia Bednarczyk"
output: html_notebook
---
Front Matter:
```{r}
rm(list=ls())
library(readr)
library(tidyverse)
library(DataComputing)
library(ggplot2)
library(dplyr)
```



Data Access:

```{r}
primarymath <- read_csv("student-mat.csv")
head(primarymath)

primarypor <- read_csv("student-por.csv")
head(primarypor)

secondary <- read_csv("StudentsPerformance.csv")
head(secondary)
```

Data Wrangling:

```{r}
# Add variable that specifies what subject
primarymath$subject <- "math"
primarypor$subject <- "portuguese"

# Combine the two dataframes into one
primarymerged <- 
  rbind(primarymath ,primarypor)

# Renaming observations to prepare for join, changing into 3 groups; 1= some high school, 2= high school degree, 3= college degree
 primarymerged$Medu[primarymerged$Medu==c("0")] <- "1"
 primarymerged$Medu[primarymerged$Medu==c("2")] <- "1"
 primarymerged$Medu[primarymerged$Medu=="3"] <- "2"
 primarymerged$Medu[primarymerged$Medu==c("4")] <- "2"
 
 primarymerged$Fedu[primarymerged$Fedu==c("0")] <- "1"
 primarymerged$Fedu[primarymerged$Fedu==c("2")] <- "1"
 primarymerged$Fedu[primarymerged$Fedu=="3"] <- "2"
 primarymerged$Fedu[primarymerged$Fedu==c("4")] <- "3"

 secondary$`parental level of education`[secondary$`parental level of education`=="some high school"] <- "1"
 secondary$`parental level of education`[secondary$`parental level of education`=="high school"] <- "2"
 secondary$`parental level of education`[secondary$`parental level of education`=="some college"] <- "2"
 secondary$`parental level of education`[secondary$`parental level of education`=="associate's degree"] <- "3"
 secondary$`parental level of education`[secondary$`parental level of education`=="bachelor's degree"] <- "3"
 secondary$`parental level of education`[secondary$`parental level of education`=="master's degree"] <- "3"
 
 
```

```{r}
#Finding average scores for each level of parental education
 joinreadysecondary <-
secondary %>%
  rename(parentedu = `parental level of education`,
         mathscore = `math score`,
         readingscore = `reading score`,
         writingscore = `writing score`) %>%
  select(parentedu, mathscore, readingscore, writingscore) %>%
  group_by(parentedu) %>%
  summarise(avgmathscore = mean(mathscore),
            avgreadingscore = mean(readingscore),
            avgwritingscore = mean(writingscore))
  
```

```{r}
# Finding the highest level of parent education

primarymerged$parentedu <- ifelse(primarymerged$Medu>primarymerged$Fedu, primarymerged$Medu, primarymerged$Fedu)

```

```{r}
# Select variables to be used in join
joinreadyprimarymerged <-
primarymerged %>%
  select(subject, sex, age, address, parentedu, Pstatus, studytime, famsup, higher, famrel, Dalc, Walc, G1, G2, G3) %>%
  mutate(grade = (G1+G2+G3)/3)

# User defined function to round numeric variables
rounding <- function(x, digits) {
  numeric_columns <- sapply(x, mode) == 'numeric'
  x[numeric_columns] <- round(x[numeric_columns], digits)
  x
}

rounding(joinreadyprimarymerged, 2)
```

```{r}
# Joining the data frames

mergedData <-
  joinreadyprimarymerged %>%
  left_join(joinreadysecondary)
 
# Rounding average scores
rounding(mergedData, 2)
```

